# This is for production deployment on the server. Do not touch!

services:
  chatapp-backend:
    container_name: chatapp-backend
    build: .
    ports:
      - "5333:5000"
    env_file:
      - .env
    depends_on:
      - chatapp-db
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - chatapp-network

  chatapp-db:
    image: postgres:15
    container_name: chatapp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chatapp-network

networks:
  chatapp-network:
      external: true
      name: chatapp-network

volumes:
  pgdata:


